// Copyright 2024 Team 254. All Rights Reserved.
// Author: (generated by Codex)
//
// Model and datastore read/write methods for persisted display configurations.

package model

// Stores the saved configuration for a display identified by its displayId.
// The Configuration map holds display-type-specific query parameters.
type DisplayConfiguration struct {
	Id            int               `db:"id"`
	DisplayId     string
	Nickname      string
	Type          int
	Configuration map[string]string
	Persistent    bool
}

// Returns the saved configuration for the given display ID, or nil if none exists.
func (database *Database) GetDisplayConfiguration(displayId string) (*DisplayConfiguration, error) {
	allConfigs, err := database.displayConfigurationTable.getAll()
	if err != nil {
		return nil, err
	}
	for _, config := range allConfigs {
		if config.DisplayId == displayId {
			return &config, nil
		}
	}
	return nil, nil
}

// Returns all saved display configurations.
func (database *Database) GetAllDisplayConfigurations() ([]DisplayConfiguration, error) {
	return database.displayConfigurationTable.getAll()
}

// Creates or updates the saved configuration for the given display ID.
// If the configuration is marked non-persistent, any stored record is removed.
func (database *Database) SaveDisplayConfiguration(config *DisplayConfiguration) error {
	if !config.Persistent {
		return database.DeleteDisplayConfiguration(config.DisplayId)
	}

	existingConfig, err := database.GetDisplayConfiguration(config.DisplayId)
	if err != nil {
		return err
	}
	if existingConfig == nil {
		return database.displayConfigurationTable.create(config)
	}
	config.Id = existingConfig.Id
	return database.displayConfigurationTable.update(config)
}

// Deletes any saved configuration for the given display ID.
func (database *Database) DeleteDisplayConfiguration(displayId string) error {
	allConfigs, err := database.displayConfigurationTable.getAll()
	if err != nil {
		return err
	}
	for _, config := range allConfigs {
		if config.DisplayId == displayId {
			return database.displayConfigurationTable.delete(config.Id)
		}
	}
	return nil
}
