// Copyright 2024 Team 254. All Rights Reserved.
// Author: (generated by Codex)
//
// Tests for persisting display configurations.

package model

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestDisplayConfigurationCrud(t *testing.T) {
	db := SetupTestDb(t)

	config := &DisplayConfiguration{
		DisplayId:     "Blue1",
		Nickname:      "Blue One",
		Type:          2,
		Configuration: map[string]string{"station": "B1", "reversed": "false"},
		Persistent:    true,
	}
	assert.Nil(t, db.SaveDisplayConfiguration(config))

	allConfigs, err := db.GetAllDisplayConfigurations()
	assert.Nil(t, err)
	if assert.Len(t, allConfigs, 1) {
		assert.Equal(t, "Blue1", allConfigs[0].DisplayId)
		assert.Equal(t, "Blue One", allConfigs[0].Nickname)
		assert.Equal(t, 2, allConfigs[0].Type)
		assert.Equal(t, map[string]string{"station": "B1", "reversed": "false"}, allConfigs[0].Configuration)
		assert.True(t, allConfigs[0].Persistent)
	}

	loadedConfig, err := db.GetDisplayConfiguration("Blue1")
	assert.Nil(t, err)
	if assert.NotNil(t, loadedConfig) {
		assert.Equal(t, config.DisplayId, loadedConfig.DisplayId)
	}

	config.Nickname = "Updated"
	config.Type = 3
	config.Configuration["station"] = "B2"
	assert.Nil(t, db.SaveDisplayConfiguration(config))

	updatedConfig, err := db.GetDisplayConfiguration("Blue1")
	assert.Nil(t, err)
	if assert.NotNil(t, updatedConfig) {
		assert.Equal(t, "Updated", updatedConfig.Nickname)
		assert.Equal(t, 3, updatedConfig.Type)
		assert.Equal(t, map[string]string{"station": "B2", "reversed": "false"}, updatedConfig.Configuration)
		assert.True(t, updatedConfig.Persistent)
	}

	config.Persistent = false
	assert.Nil(t, db.SaveDisplayConfiguration(config))
	removedConfig, err := db.GetDisplayConfiguration("Blue1")
	assert.Nil(t, err)
	assert.Nil(t, removedConfig)
}
